// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh-wbR4XvBfZTeZqAoO9S6cHuFlwbc484',
    appId: '1:967420379280:android:537e2b196d75f022f3d815',
    messagingSenderId: '967420379280',
    projectId: 'realproton-340e3',
    databaseURL: 'https://realproton-340e3-default-rtdb.firebaseio.com',
    storageBucket: 'realproton-340e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSNdLhbci2gT9PxdVODkkpwq_fVPZKqI',
    appId: '1:967420379280:ios:efb0f117215ad750f3d815',
    messagingSenderId: '967420379280',
    projectId: 'realproton-340e3',
    databaseURL: 'https://realproton-340e3-default-rtdb.firebaseio.com',
    storageBucket: 'realproton-340e3.appspot.com',
    androidClientId: '967420379280-agn25qdaadfll91edm8s1r4nfe8pevj5.apps.googleusercontent.com',
    iosClientId: '967420379280-op78dnq64ja6c04ac781si9o7fo67fr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.realproton',
  );

}